version: '3'
services:
  frontend:
    container_name: frontend
    environment:
      - CI
    build: Dockerfiles/Frontend
    ports:
      - "8080:80"
      - "2812:2812"
    volumes:
      - ./data/frontend:/data
    
