version: '3'
services:
  web:
    container_name: web
    environment:
      - CI
    build: Dockerfiles/Frontend
    ports:
      - "8080:80"
      - "2812:2812"
    volumes:
      - ./data/web:/data
    
